// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repeated.proto

#ifndef PROTOBUF_repeated_2eproto__INCLUDED
#define PROTOBUF_repeated_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_repeated_2eproto();
void protobuf_AssignDesc_repeated_2eproto();
void protobuf_ShutdownFile_repeated_2eproto();

class Dummy;
class RepeatedMessage;

// ===================================================================

class Dummy : public ::google::protobuf::Message {
 public:
  Dummy();
  virtual ~Dummy();

  Dummy(const Dummy& from);

  inline Dummy& operator=(const Dummy& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Dummy& default_instance();

  void Swap(Dummy* other);

  // implements Message ----------------------------------------------

  Dummy* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Dummy& from);
  void MergeFrom(const Dummy& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Dummy)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_repeated_2eproto();
  friend void protobuf_AssignDesc_repeated_2eproto();
  friend void protobuf_ShutdownFile_repeated_2eproto();

  void InitAsDefaultInstance();
  static Dummy* default_instance_;
};
// -------------------------------------------------------------------

class RepeatedMessage : public ::google::protobuf::Message {
 public:
  RepeatedMessage();
  virtual ~RepeatedMessage();

  RepeatedMessage(const RepeatedMessage& from);

  inline RepeatedMessage& operator=(const RepeatedMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RepeatedMessage& default_instance();

  void Swap(RepeatedMessage* other);

  // implements Message ----------------------------------------------

  RepeatedMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RepeatedMessage& from);
  void MergeFrom(const RepeatedMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 ints = 1;
  inline int ints_size() const;
  inline void clear_ints();
  static const int kIntsFieldNumber = 1;
  inline ::google::protobuf::int32 ints(int index) const;
  inline void set_ints(int index, ::google::protobuf::int32 value);
  inline void add_ints(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ints() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ints();

  // repeated string strings = 2;
  inline int strings_size() const;
  inline void clear_strings();
  static const int kStringsFieldNumber = 2;
  inline const ::std::string& strings(int index) const;
  inline ::std::string* mutable_strings(int index);
  inline void set_strings(int index, const ::std::string& value);
  inline void set_strings(int index, const char* value);
  inline void set_strings(int index, const char* value, size_t size);
  inline ::std::string* add_strings();
  inline void add_strings(const ::std::string& value);
  inline void add_strings(const char* value);
  inline void add_strings(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& strings() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_strings();

  // repeated .Dummy msgs = 3;
  inline int msgs_size() const;
  inline void clear_msgs();
  static const int kMsgsFieldNumber = 3;
  inline const ::Dummy& msgs(int index) const;
  inline ::Dummy* mutable_msgs(int index);
  inline ::Dummy* add_msgs();
  inline const ::google::protobuf::RepeatedPtrField< ::Dummy >&
      msgs() const;
  inline ::google::protobuf::RepeatedPtrField< ::Dummy >*
      mutable_msgs();

  // @@protoc_insertion_point(class_scope:RepeatedMessage)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ints_;
  ::google::protobuf::RepeatedPtrField< ::std::string> strings_;
  ::google::protobuf::RepeatedPtrField< ::Dummy > msgs_;
  friend void  protobuf_AddDesc_repeated_2eproto();
  friend void protobuf_AssignDesc_repeated_2eproto();
  friend void protobuf_ShutdownFile_repeated_2eproto();

  void InitAsDefaultInstance();
  static RepeatedMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// Dummy

// -------------------------------------------------------------------

// RepeatedMessage

// repeated int32 ints = 1;
inline int RepeatedMessage::ints_size() const {
  return ints_.size();
}
inline void RepeatedMessage::clear_ints() {
  ints_.Clear();
}
inline ::google::protobuf::int32 RepeatedMessage::ints(int index) const {
  // @@protoc_insertion_point(field_get:RepeatedMessage.ints)
  return ints_.Get(index);
}
inline void RepeatedMessage::set_ints(int index, ::google::protobuf::int32 value) {
  ints_.Set(index, value);
  // @@protoc_insertion_point(field_set:RepeatedMessage.ints)
}
inline void RepeatedMessage::add_ints(::google::protobuf::int32 value) {
  ints_.Add(value);
  // @@protoc_insertion_point(field_add:RepeatedMessage.ints)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RepeatedMessage::ints() const {
  // @@protoc_insertion_point(field_list:RepeatedMessage.ints)
  return ints_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RepeatedMessage::mutable_ints() {
  // @@protoc_insertion_point(field_mutable_list:RepeatedMessage.ints)
  return &ints_;
}

// repeated string strings = 2;
inline int RepeatedMessage::strings_size() const {
  return strings_.size();
}
inline void RepeatedMessage::clear_strings() {
  strings_.Clear();
}
inline const ::std::string& RepeatedMessage::strings(int index) const {
  // @@protoc_insertion_point(field_get:RepeatedMessage.strings)
  return strings_.Get(index);
}
inline ::std::string* RepeatedMessage::mutable_strings(int index) {
  // @@protoc_insertion_point(field_mutable:RepeatedMessage.strings)
  return strings_.Mutable(index);
}
inline void RepeatedMessage::set_strings(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RepeatedMessage.strings)
  strings_.Mutable(index)->assign(value);
}
inline void RepeatedMessage::set_strings(int index, const char* value) {
  strings_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:RepeatedMessage.strings)
}
inline void RepeatedMessage::set_strings(int index, const char* value, size_t size) {
  strings_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:RepeatedMessage.strings)
}
inline ::std::string* RepeatedMessage::add_strings() {
  return strings_.Add();
}
inline void RepeatedMessage::add_strings(const ::std::string& value) {
  strings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:RepeatedMessage.strings)
}
inline void RepeatedMessage::add_strings(const char* value) {
  strings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:RepeatedMessage.strings)
}
inline void RepeatedMessage::add_strings(const char* value, size_t size) {
  strings_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:RepeatedMessage.strings)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
RepeatedMessage::strings() const {
  // @@protoc_insertion_point(field_list:RepeatedMessage.strings)
  return strings_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
RepeatedMessage::mutable_strings() {
  // @@protoc_insertion_point(field_mutable_list:RepeatedMessage.strings)
  return &strings_;
}

// repeated .Dummy msgs = 3;
inline int RepeatedMessage::msgs_size() const {
  return msgs_.size();
}
inline void RepeatedMessage::clear_msgs() {
  msgs_.Clear();
}
inline const ::Dummy& RepeatedMessage::msgs(int index) const {
  // @@protoc_insertion_point(field_get:RepeatedMessage.msgs)
  return msgs_.Get(index);
}
inline ::Dummy* RepeatedMessage::mutable_msgs(int index) {
  // @@protoc_insertion_point(field_mutable:RepeatedMessage.msgs)
  return msgs_.Mutable(index);
}
inline ::Dummy* RepeatedMessage::add_msgs() {
  // @@protoc_insertion_point(field_add:RepeatedMessage.msgs)
  return msgs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Dummy >&
RepeatedMessage::msgs() const {
  // @@protoc_insertion_point(field_list:RepeatedMessage.msgs)
  return msgs_;
}
inline ::google::protobuf::RepeatedPtrField< ::Dummy >*
RepeatedMessage::mutable_msgs() {
  // @@protoc_insertion_point(field_mutable_list:RepeatedMessage.msgs)
  return &msgs_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_repeated_2eproto__INCLUDED
