// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook_encode_decode.proto

#ifndef PROTOBUF_addressbook_5fencode_5fdecode_2eproto__INCLUDED
#define PROTOBUF_addressbook_5fencode_5fdecode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

class ExtEncDec;
class ContentEncDec;
class JsonContextBodyEncDec;
class PersonEncDec;
class AddressBookEncDec;

enum ExtEncDec_PhoneTypeEncDec {
  ExtEncDec_PhoneTypeEncDec_MOBILE = 0,
  ExtEncDec_PhoneTypeEncDec_HOME = 1,
  ExtEncDec_PhoneTypeEncDec_WORK = 2
};
bool ExtEncDec_PhoneTypeEncDec_IsValid(int value);
const ExtEncDec_PhoneTypeEncDec ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_MIN = ExtEncDec_PhoneTypeEncDec_MOBILE;
const ExtEncDec_PhoneTypeEncDec ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_MAX = ExtEncDec_PhoneTypeEncDec_WORK;
const int ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_ARRAYSIZE = ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_MAX + 1;

const ::google::protobuf::EnumDescriptor* ExtEncDec_PhoneTypeEncDec_descriptor();
inline const ::std::string& ExtEncDec_PhoneTypeEncDec_Name(ExtEncDec_PhoneTypeEncDec value) {
  return ::google::protobuf::internal::NameOfEnum(
    ExtEncDec_PhoneTypeEncDec_descriptor(), value);
}
inline bool ExtEncDec_PhoneTypeEncDec_Parse(
    const ::std::string& name, ExtEncDec_PhoneTypeEncDec* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExtEncDec_PhoneTypeEncDec>(
    ExtEncDec_PhoneTypeEncDec_descriptor(), name, value);
}
// ===================================================================

class ExtEncDec : public ::google::protobuf::Message {
 public:
  ExtEncDec();
  virtual ~ExtEncDec();

  ExtEncDec(const ExtEncDec& from);

  inline ExtEncDec& operator=(const ExtEncDec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExtEncDec& default_instance();

  void Swap(ExtEncDec* other);

  // implements Message ----------------------------------------------

  ExtEncDec* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExtEncDec& from);
  void MergeFrom(const ExtEncDec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ExtEncDec_PhoneTypeEncDec PhoneTypeEncDec;
  static const PhoneTypeEncDec MOBILE = ExtEncDec_PhoneTypeEncDec_MOBILE;
  static const PhoneTypeEncDec HOME = ExtEncDec_PhoneTypeEncDec_HOME;
  static const PhoneTypeEncDec WORK = ExtEncDec_PhoneTypeEncDec_WORK;
  static inline bool PhoneTypeEncDec_IsValid(int value) {
    return ExtEncDec_PhoneTypeEncDec_IsValid(value);
  }
  static const PhoneTypeEncDec PhoneTypeEncDec_MIN =
    ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_MIN;
  static const PhoneTypeEncDec PhoneTypeEncDec_MAX =
    ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_MAX;
  static const int PhoneTypeEncDec_ARRAYSIZE =
    ExtEncDec_PhoneTypeEncDec_PhoneTypeEncDec_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  PhoneTypeEncDec_descriptor() {
    return ExtEncDec_PhoneTypeEncDec_descriptor();
  }
  static inline const ::std::string& PhoneTypeEncDec_Name(PhoneTypeEncDec value) {
    return ExtEncDec_PhoneTypeEncDec_Name(value);
  }
  static inline bool PhoneTypeEncDec_Parse(const ::std::string& name,
      PhoneTypeEncDec* value) {
    return ExtEncDec_PhoneTypeEncDec_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional fixed32 Aa_ge_Z040_ = 2;
  inline bool has_aa_ge_z040_() const;
  inline void clear_aa_ge_z040_();
  static const int kAaGeZ040FieldNumber = 2;
  inline ::google::protobuf::uint32 aa_ge_z040_() const;
  inline void set_aa_ge_z040_(::google::protobuf::uint32 value);

  // optional bytes databyte_Z040_std_Z058__Z058_string_Z041_ = 3;
  inline bool has_databyte_z040_std_z058__z058_string_z041_() const;
  inline void clear_databyte_z040_std_z058__z058_string_z041_();
  static const int kDatabyteZ040StdZ058Z058StringZ041FieldNumber = 3;
  inline const ::std::string& databyte_z040_std_z058__z058_string_z041_() const;
  inline void set_databyte_z040_std_z058__z058_string_z041_(const ::std::string& value);
  inline void set_databyte_z040_std_z058__z058_string_z041_(const char* value);
  inline void set_databyte_z040_std_z058__z058_string_z041_(const void* value, size_t size);
  inline ::std::string* mutable_databyte_z040_std_z058__z058_string_z041_();
  inline ::std::string* release_databyte_z040_std_z058__z058_string_z041_();
  inline void set_allocated_databyte_z040_std_z058__z058_string_z041_(::std::string* databyte_z040_std_z058__z058_string_z041_);

  // optional .ExtEncDec.PhoneTypeEncDec enum_Z045__Z045_type = 4 [default = HOME];
  inline bool has_enum_z045__z045_type() const;
  inline void clear_enum_z045__z045_type();
  static const int kEnumZ045Z045TypeFieldNumber = 4;
  inline ::ExtEncDec_PhoneTypeEncDec enum_z045__z045_type() const;
  inline void set_enum_z045__z045_type(::ExtEncDec_PhoneTypeEncDec value);

  // @@protoc_insertion_point(class_scope:ExtEncDec)
 private:
  inline void set_has_aa_ge_z040_();
  inline void clear_has_aa_ge_z040_();
  inline void set_has_databyte_z040_std_z058__z058_string_z041_();
  inline void clear_has_databyte_z040_std_z058__z058_string_z041_();
  inline void set_has_enum_z045__z045_type();
  inline void clear_has_enum_z045__z045_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* databyte_z040_std_z058__z058_string_z041__;
  ::google::protobuf::uint32 aa_ge_z040__;
  int enum_z045__z045_type_;
  friend void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

  void InitAsDefaultInstance();
  static ExtEncDec* default_instance_;
};
// -------------------------------------------------------------------

class ContentEncDec : public ::google::protobuf::Message {
 public:
  ContentEncDec();
  virtual ~ContentEncDec();

  ContentEncDec(const ContentEncDec& from);

  inline ContentEncDec& operator=(const ContentEncDec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ContentEncDec& default_instance();

  void Swap(ContentEncDec* other);

  // implements Message ----------------------------------------------

  ContentEncDec* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ContentEncDec& from);
  void MergeFrom(const ContentEncDec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string uid_Z042_ = 1;
  inline bool has_uid_z042_() const;
  inline void clear_uid_z042_();
  static const int kUidZ042FieldNumber = 1;
  inline const ::std::string& uid_z042_() const;
  inline void set_uid_z042_(const ::std::string& value);
  inline void set_uid_z042_(const char* value);
  inline void set_uid_z042_(const char* value, size_t size);
  inline ::std::string* mutable_uid_z042_();
  inline ::std::string* release_uid_z042_();
  inline void set_allocated_uid_z042_(::std::string* uid_z042_);

  // required float Distance_info_ = 16;
  inline bool has_distance_info_() const;
  inline void clear_distance_info_();
  static const int kDistanceInfoFieldNumber = 16;
  inline float distance_info_() const;
  inline void set_distance_info_(float value);

  // optional .ExtEncDec _ext_Z037_T_ = 17;
  inline bool has__ext_z037_t_() const;
  inline void clear__ext_z037_t_();
  static const int kExtZ037TFieldNumber = 17;
  inline const ::ExtEncDec& _ext_z037_t_() const;
  inline ::ExtEncDec* mutable__ext_z037_t_();
  inline ::ExtEncDec* release__ext_z037_t_();
  inline void set_allocated__ext_z037_t_(::ExtEncDec* _ext_z037_t_);

  // @@protoc_insertion_point(class_scope:ContentEncDec)
 private:
  inline void set_has_uid_z042_();
  inline void clear_has_uid_z042_();
  inline void set_has_distance_info_();
  inline void clear_has_distance_info_();
  inline void set_has__ext_z037_t_();
  inline void clear_has__ext_z037_t_();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* uid_z042__;
  ::ExtEncDec* _ext_z037_t__;
  float distance_info__;
  friend void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

  void InitAsDefaultInstance();
  static ContentEncDec* default_instance_;
};
// -------------------------------------------------------------------

class JsonContextBodyEncDec : public ::google::protobuf::Message {
 public:
  JsonContextBodyEncDec();
  virtual ~JsonContextBodyEncDec();

  JsonContextBodyEncDec(const JsonContextBodyEncDec& from);

  inline JsonContextBodyEncDec& operator=(const JsonContextBodyEncDec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JsonContextBodyEncDec& default_instance();

  void Swap(JsonContextBodyEncDec* other);

  // implements Message ----------------------------------------------

  JsonContextBodyEncDec* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JsonContextBodyEncDec& from);
  void MergeFrom(const JsonContextBodyEncDec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string info = 6;
  inline int info_size() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 6;
  inline const ::std::string& info(int index) const;
  inline ::std::string* mutable_info(int index);
  inline void set_info(int index, const ::std::string& value);
  inline void set_info(int index, const char* value);
  inline void set_info(int index, const char* value, size_t size);
  inline ::std::string* add_info();
  inline void add_info(const ::std::string& value);
  inline void add_info(const char* value);
  inline void add_info(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& info() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_info();

  // optional int64 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int64 type() const;
  inline void set_type(::google::protobuf::int64 value);

  // repeated int32 data_Z058_array = 5;
  inline int data_z058_array_size() const;
  inline void clear_data_z058_array();
  static const int kDataZ058ArrayFieldNumber = 5;
  inline ::google::protobuf::int32 data_z058_array(int index) const;
  inline void set_data_z058_array(int index, ::google::protobuf::int32 value);
  inline void add_data_z058_array(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data_z058_array() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data_z058_array();

  // required bool judge = 2;
  inline bool has_judge() const;
  inline void clear_judge();
  static const int kJudgeFieldNumber = 2;
  inline bool judge() const;
  inline void set_judge(bool value);

  // optional double spur = 3;
  inline bool has_spur() const;
  inline void clear_spur();
  static const int kSpurFieldNumber = 3;
  inline double spur() const;
  inline void set_spur(double value);

  // repeated .ContentEncDec _Z064_Content_Test_Z037__Z064_ = 4;
  inline int _z064_content_test_z037__z064__size() const;
  inline void clear__z064_content_test_z037__z064_();
  static const int kZ064ContentTestZ037Z064FieldNumber = 4;
  inline const ::ContentEncDec& _z064_content_test_z037__z064_(int index) const;
  inline ::ContentEncDec* mutable__z064_content_test_z037__z064_(int index);
  inline ::ContentEncDec* add__z064_content_test_z037__z064_();
  inline const ::google::protobuf::RepeatedPtrField< ::ContentEncDec >&
      _z064_content_test_z037__z064_() const;
  inline ::google::protobuf::RepeatedPtrField< ::ContentEncDec >*
      mutable__z064_content_test_z037__z064_();

  // @@protoc_insertion_point(class_scope:JsonContextBodyEncDec)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_judge();
  inline void clear_has_judge();
  inline void set_has_spur();
  inline void clear_has_spur();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> info_;
  ::google::protobuf::int64 type_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_z058_array_;
  double spur_;
  ::google::protobuf::RepeatedPtrField< ::ContentEncDec > _z064_content_test_z037__z064__;
  bool judge_;
  friend void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

  void InitAsDefaultInstance();
  static JsonContextBodyEncDec* default_instance_;
};
// -------------------------------------------------------------------

class PersonEncDec : public ::google::protobuf::Message {
 public:
  PersonEncDec();
  virtual ~PersonEncDec();

  PersonEncDec(const PersonEncDec& from);

  inline PersonEncDec& operator=(const PersonEncDec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PersonEncDec& default_instance();

  void Swap(PersonEncDec* other);

  // implements Message ----------------------------------------------

  PersonEncDec* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PersonEncDec& from);
  void MergeFrom(const PersonEncDec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional .JsonContextBodyEncDec json_body = 18;
  inline bool has_json_body() const;
  inline void clear_json_body();
  static const int kJsonBodyFieldNumber = 18;
  inline const ::JsonContextBodyEncDec& json_body() const;
  inline ::JsonContextBodyEncDec* mutable_json_body();
  inline ::JsonContextBodyEncDec* release_json_body();
  inline void set_allocated_json_body(::JsonContextBodyEncDec* json_body);

  // @@protoc_insertion_point(class_scope:PersonEncDec)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_json_body();
  inline void clear_has_json_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::JsonContextBodyEncDec* json_body_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

  void InitAsDefaultInstance();
  static PersonEncDec* default_instance_;
};
// -------------------------------------------------------------------

class AddressBookEncDec : public ::google::protobuf::Message {
 public:
  AddressBookEncDec();
  virtual ~AddressBookEncDec();

  AddressBookEncDec(const AddressBookEncDec& from);

  inline AddressBookEncDec& operator=(const AddressBookEncDec& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddressBookEncDec& default_instance();

  void Swap(AddressBookEncDec* other);

  // implements Message ----------------------------------------------

  AddressBookEncDec* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddressBookEncDec& from);
  void MergeFrom(const AddressBookEncDec& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PersonEncDec person = 1;
  inline int person_size() const;
  inline void clear_person();
  static const int kPersonFieldNumber = 1;
  inline const ::PersonEncDec& person(int index) const;
  inline ::PersonEncDec* mutable_person(int index);
  inline ::PersonEncDec* add_person();
  inline const ::google::protobuf::RepeatedPtrField< ::PersonEncDec >&
      person() const;
  inline ::google::protobuf::RepeatedPtrField< ::PersonEncDec >*
      mutable_person();

  // @@protoc_insertion_point(class_scope:AddressBookEncDec)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::PersonEncDec > person_;
  friend void  protobuf_AddDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_AssignDesc_addressbook_5fencode_5fdecode_2eproto();
  friend void protobuf_ShutdownFile_addressbook_5fencode_5fdecode_2eproto();

  void InitAsDefaultInstance();
  static AddressBookEncDec* default_instance_;
};
// ===================================================================


// ===================================================================

// ExtEncDec

// optional fixed32 Aa_ge_Z040_ = 2;
inline bool ExtEncDec::has_aa_ge_z040_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ExtEncDec::set_has_aa_ge_z040_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ExtEncDec::clear_has_aa_ge_z040_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ExtEncDec::clear_aa_ge_z040_() {
  aa_ge_z040__ = 0u;
  clear_has_aa_ge_z040_();
}
inline ::google::protobuf::uint32 ExtEncDec::aa_ge_z040_() const {
  // @@protoc_insertion_point(field_get:ExtEncDec.Aa_ge_Z040_)
  return aa_ge_z040__;
}
inline void ExtEncDec::set_aa_ge_z040_(::google::protobuf::uint32 value) {
  set_has_aa_ge_z040_();
  aa_ge_z040__ = value;
  // @@protoc_insertion_point(field_set:ExtEncDec.Aa_ge_Z040_)
}

// optional bytes databyte_Z040_std_Z058__Z058_string_Z041_ = 3;
inline bool ExtEncDec::has_databyte_z040_std_z058__z058_string_z041_() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ExtEncDec::set_has_databyte_z040_std_z058__z058_string_z041_() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ExtEncDec::clear_has_databyte_z040_std_z058__z058_string_z041_() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ExtEncDec::clear_databyte_z040_std_z058__z058_string_z041_() {
  if (databyte_z040_std_z058__z058_string_z041__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    databyte_z040_std_z058__z058_string_z041__->clear();
  }
  clear_has_databyte_z040_std_z058__z058_string_z041_();
}
inline const ::std::string& ExtEncDec::databyte_z040_std_z058__z058_string_z041_() const {
  // @@protoc_insertion_point(field_get:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
  return *databyte_z040_std_z058__z058_string_z041__;
}
inline void ExtEncDec::set_databyte_z040_std_z058__z058_string_z041_(const ::std::string& value) {
  set_has_databyte_z040_std_z058__z058_string_z041_();
  if (databyte_z040_std_z058__z058_string_z041__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    databyte_z040_std_z058__z058_string_z041__ = new ::std::string;
  }
  databyte_z040_std_z058__z058_string_z041__->assign(value);
  // @@protoc_insertion_point(field_set:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
}
inline void ExtEncDec::set_databyte_z040_std_z058__z058_string_z041_(const char* value) {
  set_has_databyte_z040_std_z058__z058_string_z041_();
  if (databyte_z040_std_z058__z058_string_z041__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    databyte_z040_std_z058__z058_string_z041__ = new ::std::string;
  }
  databyte_z040_std_z058__z058_string_z041__->assign(value);
  // @@protoc_insertion_point(field_set_char:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
}
inline void ExtEncDec::set_databyte_z040_std_z058__z058_string_z041_(const void* value, size_t size) {
  set_has_databyte_z040_std_z058__z058_string_z041_();
  if (databyte_z040_std_z058__z058_string_z041__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    databyte_z040_std_z058__z058_string_z041__ = new ::std::string;
  }
  databyte_z040_std_z058__z058_string_z041__->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
}
inline ::std::string* ExtEncDec::mutable_databyte_z040_std_z058__z058_string_z041_() {
  set_has_databyte_z040_std_z058__z058_string_z041_();
  if (databyte_z040_std_z058__z058_string_z041__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    databyte_z040_std_z058__z058_string_z041__ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
  return databyte_z040_std_z058__z058_string_z041__;
}
inline ::std::string* ExtEncDec::release_databyte_z040_std_z058__z058_string_z041_() {
  clear_has_databyte_z040_std_z058__z058_string_z041_();
  if (databyte_z040_std_z058__z058_string_z041__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = databyte_z040_std_z058__z058_string_z041__;
    databyte_z040_std_z058__z058_string_z041__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ExtEncDec::set_allocated_databyte_z040_std_z058__z058_string_z041_(::std::string* databyte_z040_std_z058__z058_string_z041_) {
  if (databyte_z040_std_z058__z058_string_z041__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete databyte_z040_std_z058__z058_string_z041__;
  }
  if (databyte_z040_std_z058__z058_string_z041_) {
    set_has_databyte_z040_std_z058__z058_string_z041_();
    databyte_z040_std_z058__z058_string_z041__ = databyte_z040_std_z058__z058_string_z041_;
  } else {
    clear_has_databyte_z040_std_z058__z058_string_z041_();
    databyte_z040_std_z058__z058_string_z041__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ExtEncDec.databyte_Z040_std_Z058__Z058_string_Z041_)
}

// optional .ExtEncDec.PhoneTypeEncDec enum_Z045__Z045_type = 4 [default = HOME];
inline bool ExtEncDec::has_enum_z045__z045_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ExtEncDec::set_has_enum_z045__z045_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ExtEncDec::clear_has_enum_z045__z045_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ExtEncDec::clear_enum_z045__z045_type() {
  enum_z045__z045_type_ = 1;
  clear_has_enum_z045__z045_type();
}
inline ::ExtEncDec_PhoneTypeEncDec ExtEncDec::enum_z045__z045_type() const {
  // @@protoc_insertion_point(field_get:ExtEncDec.enum_Z045__Z045_type)
  return static_cast< ::ExtEncDec_PhoneTypeEncDec >(enum_z045__z045_type_);
}
inline void ExtEncDec::set_enum_z045__z045_type(::ExtEncDec_PhoneTypeEncDec value) {
  assert(::ExtEncDec_PhoneTypeEncDec_IsValid(value));
  set_has_enum_z045__z045_type();
  enum_z045__z045_type_ = value;
  // @@protoc_insertion_point(field_set:ExtEncDec.enum_Z045__Z045_type)
}

// -------------------------------------------------------------------

// ContentEncDec

// optional string uid_Z042_ = 1;
inline bool ContentEncDec::has_uid_z042_() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ContentEncDec::set_has_uid_z042_() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ContentEncDec::clear_has_uid_z042_() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ContentEncDec::clear_uid_z042_() {
  if (uid_z042__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_z042__->clear();
  }
  clear_has_uid_z042_();
}
inline const ::std::string& ContentEncDec::uid_z042_() const {
  // @@protoc_insertion_point(field_get:ContentEncDec.uid_Z042_)
  return *uid_z042__;
}
inline void ContentEncDec::set_uid_z042_(const ::std::string& value) {
  set_has_uid_z042_();
  if (uid_z042__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_z042__ = new ::std::string;
  }
  uid_z042__->assign(value);
  // @@protoc_insertion_point(field_set:ContentEncDec.uid_Z042_)
}
inline void ContentEncDec::set_uid_z042_(const char* value) {
  set_has_uid_z042_();
  if (uid_z042__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_z042__ = new ::std::string;
  }
  uid_z042__->assign(value);
  // @@protoc_insertion_point(field_set_char:ContentEncDec.uid_Z042_)
}
inline void ContentEncDec::set_uid_z042_(const char* value, size_t size) {
  set_has_uid_z042_();
  if (uid_z042__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_z042__ = new ::std::string;
  }
  uid_z042__->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ContentEncDec.uid_Z042_)
}
inline ::std::string* ContentEncDec::mutable_uid_z042_() {
  set_has_uid_z042_();
  if (uid_z042__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_z042__ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ContentEncDec.uid_Z042_)
  return uid_z042__;
}
inline ::std::string* ContentEncDec::release_uid_z042_() {
  clear_has_uid_z042_();
  if (uid_z042__ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = uid_z042__;
    uid_z042__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ContentEncDec::set_allocated_uid_z042_(::std::string* uid_z042_) {
  if (uid_z042__ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uid_z042__;
  }
  if (uid_z042_) {
    set_has_uid_z042_();
    uid_z042__ = uid_z042_;
  } else {
    clear_has_uid_z042_();
    uid_z042__ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ContentEncDec.uid_Z042_)
}

// required float Distance_info_ = 16;
inline bool ContentEncDec::has_distance_info_() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ContentEncDec::set_has_distance_info_() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ContentEncDec::clear_has_distance_info_() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ContentEncDec::clear_distance_info_() {
  distance_info__ = 0;
  clear_has_distance_info_();
}
inline float ContentEncDec::distance_info_() const {
  // @@protoc_insertion_point(field_get:ContentEncDec.Distance_info_)
  return distance_info__;
}
inline void ContentEncDec::set_distance_info_(float value) {
  set_has_distance_info_();
  distance_info__ = value;
  // @@protoc_insertion_point(field_set:ContentEncDec.Distance_info_)
}

// optional .ExtEncDec _ext_Z037_T_ = 17;
inline bool ContentEncDec::has__ext_z037_t_() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ContentEncDec::set_has__ext_z037_t_() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ContentEncDec::clear_has__ext_z037_t_() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ContentEncDec::clear__ext_z037_t_() {
  if (_ext_z037_t__ != NULL) _ext_z037_t__->::ExtEncDec::Clear();
  clear_has__ext_z037_t_();
}
inline const ::ExtEncDec& ContentEncDec::_ext_z037_t_() const {
  // @@protoc_insertion_point(field_get:ContentEncDec._ext_Z037_T_)
  return _ext_z037_t__ != NULL ? *_ext_z037_t__ : *default_instance_->_ext_z037_t__;
}
inline ::ExtEncDec* ContentEncDec::mutable__ext_z037_t_() {
  set_has__ext_z037_t_();
  if (_ext_z037_t__ == NULL) _ext_z037_t__ = new ::ExtEncDec;
  // @@protoc_insertion_point(field_mutable:ContentEncDec._ext_Z037_T_)
  return _ext_z037_t__;
}
inline ::ExtEncDec* ContentEncDec::release__ext_z037_t_() {
  clear_has__ext_z037_t_();
  ::ExtEncDec* temp = _ext_z037_t__;
  _ext_z037_t__ = NULL;
  return temp;
}
inline void ContentEncDec::set_allocated__ext_z037_t_(::ExtEncDec* _ext_z037_t_) {
  delete _ext_z037_t__;
  _ext_z037_t__ = _ext_z037_t_;
  if (_ext_z037_t_) {
    set_has__ext_z037_t_();
  } else {
    clear_has__ext_z037_t_();
  }
  // @@protoc_insertion_point(field_set_allocated:ContentEncDec._ext_Z037_T_)
}

// -------------------------------------------------------------------

// JsonContextBodyEncDec

// repeated string info = 6;
inline int JsonContextBodyEncDec::info_size() const {
  return info_.size();
}
inline void JsonContextBodyEncDec::clear_info() {
  info_.Clear();
}
inline const ::std::string& JsonContextBodyEncDec::info(int index) const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec.info)
  return info_.Get(index);
}
inline ::std::string* JsonContextBodyEncDec::mutable_info(int index) {
  // @@protoc_insertion_point(field_mutable:JsonContextBodyEncDec.info)
  return info_.Mutable(index);
}
inline void JsonContextBodyEncDec::set_info(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:JsonContextBodyEncDec.info)
  info_.Mutable(index)->assign(value);
}
inline void JsonContextBodyEncDec::set_info(int index, const char* value) {
  info_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:JsonContextBodyEncDec.info)
}
inline void JsonContextBodyEncDec::set_info(int index, const char* value, size_t size) {
  info_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JsonContextBodyEncDec.info)
}
inline ::std::string* JsonContextBodyEncDec::add_info() {
  return info_.Add();
}
inline void JsonContextBodyEncDec::add_info(const ::std::string& value) {
  info_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:JsonContextBodyEncDec.info)
}
inline void JsonContextBodyEncDec::add_info(const char* value) {
  info_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:JsonContextBodyEncDec.info)
}
inline void JsonContextBodyEncDec::add_info(const char* value, size_t size) {
  info_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:JsonContextBodyEncDec.info)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
JsonContextBodyEncDec::info() const {
  // @@protoc_insertion_point(field_list:JsonContextBodyEncDec.info)
  return info_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
JsonContextBodyEncDec::mutable_info() {
  // @@protoc_insertion_point(field_mutable_list:JsonContextBodyEncDec.info)
  return &info_;
}

// optional int64 type = 1;
inline bool JsonContextBodyEncDec::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void JsonContextBodyEncDec::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void JsonContextBodyEncDec::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void JsonContextBodyEncDec::clear_type() {
  type_ = GOOGLE_LONGLONG(0);
  clear_has_type();
}
inline ::google::protobuf::int64 JsonContextBodyEncDec::type() const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec.type)
  return type_;
}
inline void JsonContextBodyEncDec::set_type(::google::protobuf::int64 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:JsonContextBodyEncDec.type)
}

// repeated int32 data_Z058_array = 5;
inline int JsonContextBodyEncDec::data_z058_array_size() const {
  return data_z058_array_.size();
}
inline void JsonContextBodyEncDec::clear_data_z058_array() {
  data_z058_array_.Clear();
}
inline ::google::protobuf::int32 JsonContextBodyEncDec::data_z058_array(int index) const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec.data_Z058_array)
  return data_z058_array_.Get(index);
}
inline void JsonContextBodyEncDec::set_data_z058_array(int index, ::google::protobuf::int32 value) {
  data_z058_array_.Set(index, value);
  // @@protoc_insertion_point(field_set:JsonContextBodyEncDec.data_Z058_array)
}
inline void JsonContextBodyEncDec::add_data_z058_array(::google::protobuf::int32 value) {
  data_z058_array_.Add(value);
  // @@protoc_insertion_point(field_add:JsonContextBodyEncDec.data_Z058_array)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
JsonContextBodyEncDec::data_z058_array() const {
  // @@protoc_insertion_point(field_list:JsonContextBodyEncDec.data_Z058_array)
  return data_z058_array_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
JsonContextBodyEncDec::mutable_data_z058_array() {
  // @@protoc_insertion_point(field_mutable_list:JsonContextBodyEncDec.data_Z058_array)
  return &data_z058_array_;
}

// required bool judge = 2;
inline bool JsonContextBodyEncDec::has_judge() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void JsonContextBodyEncDec::set_has_judge() {
  _has_bits_[0] |= 0x00000008u;
}
inline void JsonContextBodyEncDec::clear_has_judge() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void JsonContextBodyEncDec::clear_judge() {
  judge_ = false;
  clear_has_judge();
}
inline bool JsonContextBodyEncDec::judge() const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec.judge)
  return judge_;
}
inline void JsonContextBodyEncDec::set_judge(bool value) {
  set_has_judge();
  judge_ = value;
  // @@protoc_insertion_point(field_set:JsonContextBodyEncDec.judge)
}

// optional double spur = 3;
inline bool JsonContextBodyEncDec::has_spur() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void JsonContextBodyEncDec::set_has_spur() {
  _has_bits_[0] |= 0x00000010u;
}
inline void JsonContextBodyEncDec::clear_has_spur() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void JsonContextBodyEncDec::clear_spur() {
  spur_ = 0;
  clear_has_spur();
}
inline double JsonContextBodyEncDec::spur() const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec.spur)
  return spur_;
}
inline void JsonContextBodyEncDec::set_spur(double value) {
  set_has_spur();
  spur_ = value;
  // @@protoc_insertion_point(field_set:JsonContextBodyEncDec.spur)
}

// repeated .ContentEncDec _Z064_Content_Test_Z037__Z064_ = 4;
inline int JsonContextBodyEncDec::_z064_content_test_z037__z064__size() const {
  return _z064_content_test_z037__z064__.size();
}
inline void JsonContextBodyEncDec::clear__z064_content_test_z037__z064_() {
  _z064_content_test_z037__z064__.Clear();
}
inline const ::ContentEncDec& JsonContextBodyEncDec::_z064_content_test_z037__z064_(int index) const {
  // @@protoc_insertion_point(field_get:JsonContextBodyEncDec._Z064_Content_Test_Z037__Z064_)
  return _z064_content_test_z037__z064__.Get(index);
}
inline ::ContentEncDec* JsonContextBodyEncDec::mutable__z064_content_test_z037__z064_(int index) {
  // @@protoc_insertion_point(field_mutable:JsonContextBodyEncDec._Z064_Content_Test_Z037__Z064_)
  return _z064_content_test_z037__z064__.Mutable(index);
}
inline ::ContentEncDec* JsonContextBodyEncDec::add__z064_content_test_z037__z064_() {
  // @@protoc_insertion_point(field_add:JsonContextBodyEncDec._Z064_Content_Test_Z037__Z064_)
  return _z064_content_test_z037__z064__.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ContentEncDec >&
JsonContextBodyEncDec::_z064_content_test_z037__z064_() const {
  // @@protoc_insertion_point(field_list:JsonContextBodyEncDec._Z064_Content_Test_Z037__Z064_)
  return _z064_content_test_z037__z064__;
}
inline ::google::protobuf::RepeatedPtrField< ::ContentEncDec >*
JsonContextBodyEncDec::mutable__z064_content_test_z037__z064_() {
  // @@protoc_insertion_point(field_mutable_list:JsonContextBodyEncDec._Z064_Content_Test_Z037__Z064_)
  return &_z064_content_test_z037__z064__;
}

// -------------------------------------------------------------------

// PersonEncDec

// optional string name = 1;
inline bool PersonEncDec::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PersonEncDec::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PersonEncDec::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PersonEncDec::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PersonEncDec::name() const {
  // @@protoc_insertion_point(field_get:PersonEncDec.name)
  return *name_;
}
inline void PersonEncDec::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:PersonEncDec.name)
}
inline void PersonEncDec::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:PersonEncDec.name)
}
inline void PersonEncDec::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PersonEncDec.name)
}
inline ::std::string* PersonEncDec::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:PersonEncDec.name)
  return name_;
}
inline ::std::string* PersonEncDec::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PersonEncDec::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:PersonEncDec.name)
}

// optional int32 id = 2;
inline bool PersonEncDec::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PersonEncDec::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PersonEncDec::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PersonEncDec::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 PersonEncDec::id() const {
  // @@protoc_insertion_point(field_get:PersonEncDec.id)
  return id_;
}
inline void PersonEncDec::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:PersonEncDec.id)
}

// optional .JsonContextBodyEncDec json_body = 18;
inline bool PersonEncDec::has_json_body() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PersonEncDec::set_has_json_body() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PersonEncDec::clear_has_json_body() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PersonEncDec::clear_json_body() {
  if (json_body_ != NULL) json_body_->::JsonContextBodyEncDec::Clear();
  clear_has_json_body();
}
inline const ::JsonContextBodyEncDec& PersonEncDec::json_body() const {
  // @@protoc_insertion_point(field_get:PersonEncDec.json_body)
  return json_body_ != NULL ? *json_body_ : *default_instance_->json_body_;
}
inline ::JsonContextBodyEncDec* PersonEncDec::mutable_json_body() {
  set_has_json_body();
  if (json_body_ == NULL) json_body_ = new ::JsonContextBodyEncDec;
  // @@protoc_insertion_point(field_mutable:PersonEncDec.json_body)
  return json_body_;
}
inline ::JsonContextBodyEncDec* PersonEncDec::release_json_body() {
  clear_has_json_body();
  ::JsonContextBodyEncDec* temp = json_body_;
  json_body_ = NULL;
  return temp;
}
inline void PersonEncDec::set_allocated_json_body(::JsonContextBodyEncDec* json_body) {
  delete json_body_;
  json_body_ = json_body;
  if (json_body) {
    set_has_json_body();
  } else {
    clear_has_json_body();
  }
  // @@protoc_insertion_point(field_set_allocated:PersonEncDec.json_body)
}

// -------------------------------------------------------------------

// AddressBookEncDec

// repeated .PersonEncDec person = 1;
inline int AddressBookEncDec::person_size() const {
  return person_.size();
}
inline void AddressBookEncDec::clear_person() {
  person_.Clear();
}
inline const ::PersonEncDec& AddressBookEncDec::person(int index) const {
  // @@protoc_insertion_point(field_get:AddressBookEncDec.person)
  return person_.Get(index);
}
inline ::PersonEncDec* AddressBookEncDec::mutable_person(int index) {
  // @@protoc_insertion_point(field_mutable:AddressBookEncDec.person)
  return person_.Mutable(index);
}
inline ::PersonEncDec* AddressBookEncDec::add_person() {
  // @@protoc_insertion_point(field_add:AddressBookEncDec.person)
  return person_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PersonEncDec >&
AddressBookEncDec::person() const {
  // @@protoc_insertion_point(field_list:AddressBookEncDec.person)
  return person_;
}
inline ::google::protobuf::RepeatedPtrField< ::PersonEncDec >*
AddressBookEncDec::mutable_person() {
  // @@protoc_insertion_point(field_mutable_list:AddressBookEncDec.person)
  return &person_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ExtEncDec_PhoneTypeEncDec> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ExtEncDec_PhoneTypeEncDec>() {
  return ::ExtEncDec_PhoneTypeEncDec_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_addressbook_5fencode_5fdecode_2eproto__INCLUDED
